version: '3'

services:
  database:
    build: ./database
    container_name: sw_kanmon_db
    expose:
      - "5432"
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # 作成したボリュームをコンテナにマウント
      - volume_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES-DATABASE=postgres
      - DATABASE_HOST=localhost

  app:
    container_name: sw_kanmon_app
    build: ./app
    expose:
      - "3031"
    volumes:
      - ./app:/var/www/app
    depends_on:
      - database
    command: uwsgi --ini /var/www/app/config/uwsgi.ini

  nginx:
    container_name: sw_kanmon_nginx
    build: ./nginx
    restart: always
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    ports:
      - "8080:80"

volumes:
  volume_data:

